export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTHENTICATE_CHECK_STATE = "AUTHENTICATE_CHECK_STATE";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_START = "AUTHENTICATE_START";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_CHECK_TIMEOUT = "AUTHENTICATE_CHECK_TIMEOUT";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";
export const AUTHENTICATE_INITIATE_LOGOUT = "AUTHENTICATE_INITIATE_LOGOUT";
export const AUTHENTICATE_LOGOUT = "AUTHENTICATE_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
